const surface = "#ffffff";
const textColor = "#111827";
const muted = "#6b7280";
const ring = "#6366f1";
const accent = "#7c3aed";
const accent2 = "#22d3ee";
const border = "#e5e7eb";
const shadow = "0 8px 24px rgba(2,6,23,.08)";

player()

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === "RUN_EXTRACTION") {
    extractAndSendArticle(message.persona, message.absurd_level);
    sendResponse({ status: "Extraction started" });
  }
  return true;
});

async function getPersonaResponse(article, persona, absurd_level, personaDescription){
  const response = await fetch("http://localhost:8000/text/", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        title: article.title,
        persona: persona,
        absurd_level: absurd_level,
        personaDescription: personaDescription,
        textContent: article.textContent
      })
    });

    if (!response.ok) {
      console.error("❌ Server responded with an error:", response.status, response.statusText);
      return;
    }

    const result = await response.json();
    return result.msg;
}

async function insertNewHeader(generated_text) {
  header = document.querySelector("h1");
  if (header) {

    if (document.getElementById("przeinaczai")) {
      div = document.getElementById("przeinaczai");
      div.getElementsByTagName("p")[0].innerHTML = generated_text;
    } else {
      // create new element above this h1
      // Główny kontener bannera
      const banner = document.createElement("div");
      banner.id = "przeinaczai";
      banner.style.position = "relative";
      banner.style.background = surface;
      banner.style.border = `1px solid ${border}`;
      banner.style.borderRadius = "12px";
      banner.style.padding = "20px 16px 14px";
      banner.style.boxShadow = `0 8px 24px #8d63d745`;
      banner.style.marginBottom = "20px";
      banner.style.overflow = "hidden";
      banner.style.opacity = "0";
      banner.style.transform = "translateY(10px)";
      banner.style.transition = "opacity 0.4s ease, transform 0.4s ease";

      // Main text
      const text = document.createElement("p");
      text.innerHTML = generated_text;
      text.style.margin = "0 0 14px";
      text.style.fontSize = "13px";
      text.style.lineHeight = "1.5";
      text.style.color = textColor;
      banner.appendChild(text);

      // Pasek gradientowy na dole
      const bar = document.createElement("div");
      bar.style.position = "absolute";
      bar.style.bottom = "0";
      bar.style.left = "0";
      bar.style.right = "0";
      bar.style.height = "3px";
      bar.style.background = `linear-gradient(90deg, ${accent}, ${accent2})`;
      bar.style.borderBottomLeftRadius = "inherit";
      bar.style.borderBottomRightRadius = "inherit";
      banner.appendChild(bar);


      // --- Footer area inside banner ---
      const footer = document.createElement("div");
      footer.style.display = "flex";
      footer.style.alignItems = "center";
      footer.style.justifyContent = "space-between";
      footer.style.marginTop = "10px";
      footer.style.paddingTop = "10px";
      footer.style.borderTop = `1px solid ${border}`;

      // Left side: avatar + label
      const left = document.createElement("div");
      left.style.display = "flex";
      left.style.alignItems = "center";
      left.style.gap = "8px";

      const avatar = document.createElement("div");
      avatar.style.width = "28px";
      avatar.style.height = "28px";
      avatar.style.borderRadius = "50%";
      avatar.style.background = `conic-gradient(from 210deg, ${accent}, ${accent2})`;
      avatar.style.boxShadow = shadow;
      avatar.style.display = "grid";
      avatar.style.placeItems = "center";
      avatar.style.color = "#fff";
      avatar.style.fontWeight = "700";
      avatar.style.fontSize = "13px";
      avatar.textContent = "A"; // author initial

      const AIlabel = document.createElement("span");
      AIlabel.textContent = "Generated by przeinaczAI";
      AIlabel.style.fontSize = "12px";
      AIlabel.style.color = muted;
      AIlabel.style.letterSpacing = ".2px";

      left.appendChild(avatar);
      left.appendChild(AIlabel);

      // Right side: share button
      const shareBtn = document.createElement("button");
      shareBtn.textContent = "Share";
      shareBtn.style.padding = "6px 12px";
      shareBtn.style.border = "none";
      shareBtn.style.borderRadius = "8px";
      shareBtn.style.background = `linear-gradient(90deg, ${accent}, ${accent2})`;
      shareBtn.style.color = "#fff";
      shareBtn.style.fontSize = "12px";
      shareBtn.style.fontWeight = "600";
      shareBtn.style.letterSpacing = ".2px";
      shareBtn.style.boxShadow = shadow;
      shareBtn.style.cursor = "pointer";
      shareBtn.style.transition = "transform .1s ease";
      shareBtn.addEventListener("mouseenter", () => (shareBtn.style.transform = "translateY(-1px)"));
      shareBtn.addEventListener("mouseleave", () => (shareBtn.style.transform = "translateY(0)"));

      footer.appendChild(left);
      footer.appendChild(shareBtn);
      banner.appendChild(footer);

      // Wstawienie przed <h1>
      header.parentNode.insertBefore(banner, header);

      // Animowane wejście
      requestAnimationFrame(() => {
        banner.style.opacity = "1";
        banner.style.transform = "translateY(0)";
      });
    }
    
  } else {
    console.error("⚠️ No <h1> element found to insert the new header above. ⚠️");
  }
}

function doesCachedValueExist(url, persona, absurd_level){
  const key = url + "_" + persona + "_" + absurd_level;
  if (sessionStorage.getItem(key)) {
    return true;
  }
  return false;
}


function getCachedValue(url, persona, absurd_level){
  const key = url + "_" + persona + "_" + absurd_level;
  return sessionStorage.getItem(key);
}

function setCachedValue(url, persona, absurd_level, value){
  const key = url + "_" + persona + "_" + absurd_level;
  sessionStorage.setItem(key, value);
}

async function extractAndSendArticle(persona, absurd_level) {
  const clone = document.cloneNode(true);
  const reader = new Readability(clone);
  const article = reader.parse();

  if (!article) {
    console.error("⚠️ No article content could be extracted. ⚠️");
    return;
  }

  response = ""
  if (doesCachedValueExist(window.location.href, persona, absurd_level)) {
    response = getCachedValue(window.location.href, persona, absurd_level);
    console.log(response);
    alert("CACHE " + persona + " " + absurd_level);
  } else {
    response = getPersonaResponse(article, persona, absurd_level, "Nie cenzuruj się, używaj wulgaryzmów i mów jak kapitan bomba z kreskówki.");
    setCachedValue(window.location.href, persona, absurd_level, await response);
    alert("SERVER " + persona + " " + absurd_level);
  }

  insertNewHeader(await response);
}
