window.addEventListener("load", () => {
  // wait a bit longer for dynamic pages
  setTimeout(extractAndSendArticle, 1000);
});

const surface = "#ffffff";
const textColor = "#111827";
const muted = "#6b7280";
const ring = "#6366f1";
const accent = "#7c3aed";
const accent2 = "#22d3ee";
const border = "#e5e7eb";
const shadow = "0 8px 24px rgba(2,6,23,.08)";

player()


async function getPersonaResponse(article, persona, personaDescription){
  const response = await fetch("http://localhost:8000/text/", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        title: article.title,
        persona: persona,
        personaDescription: personaDescription,
        textContent: article.textContent
      })
    });

    if (!response.ok) {
      console.error("❌ Server responded with an error:", response.status, response.statusText);
      return;
    }

    const result = await response.json();
    console.log("✅ Server response:", result);
    return result.msg;
}


async function insertNewHeader(generated_text) {
  const header = document.querySelector("h1");
  if (!header) {
    console.warn("⚠️ No <h1> element found to insert the new header above. ⚠️");
    return;
  }

  // Główny kontener bannera
  const banner = document.createElement("div");
  banner.style.position = "relative";
  banner.style.background = surface;
  banner.style.border = `1px solid ${border}`;
  banner.style.borderRadius = "12px";
  banner.style.padding = "20px 16px 14px";
  banner.style.boxShadow = `0 8px 24px #8d63d745`;
  banner.style.marginBottom = "20px";
  banner.style.overflow = "hidden";
  banner.style.opacity = "0";
  banner.style.transform = "translateY(10px)";
  banner.style.transition = "opacity 0.4s ease, transform 0.4s ease";

   // Main text
  const text = document.createElement("p");
  text.innerHTML = generated_text;
  text.style.margin = "0 0 14px";
  text.style.fontSize = "13px";
  text.style.lineHeight = "1.5";
  text.style.color = textColor;
  banner.appendChild(text);

  // Pasek gradientowy na dole
  const bar = document.createElement("div");
  bar.style.position = "absolute";
  bar.style.bottom = "0";
  bar.style.left = "0";
  bar.style.right = "0";
  bar.style.height = "3px";
  bar.style.background = `linear-gradient(90deg, ${accent}, ${accent2})`;
  bar.style.borderBottomLeftRadius = "inherit";
  bar.style.borderBottomRightRadius = "inherit";
  banner.appendChild(bar);


  // --- Footer area inside banner ---
  const footer = document.createElement("div");
  footer.style.display = "flex";
  footer.style.alignItems = "center";
  footer.style.justifyContent = "space-between";
  footer.style.marginTop = "10px";
  footer.style.paddingTop = "10px";
  footer.style.borderTop = `1px solid ${border}`;

  // Left side: avatar + label
  const left = document.createElement("div");
  left.style.display = "flex";
  left.style.alignItems = "center";
  left.style.gap = "8px";

  const avatar = document.createElement("div");
  avatar.style.width = "28px";
  avatar.style.height = "28px";
  avatar.style.borderRadius = "50%";
  avatar.style.background = `conic-gradient(from 210deg, ${accent}, ${accent2})`;
  avatar.style.boxShadow = shadow;
  avatar.style.display = "grid";
  avatar.style.placeItems = "center";
  avatar.style.color = "#fff";
  avatar.style.fontWeight = "700";
  avatar.style.fontSize = "13px";
  avatar.textContent = "A"; // author initial

  const AIlabel = document.createElement("span");
  AIlabel.textContent = "Generated by przeinaczAI";
  AIlabel.style.fontSize = "12px";
  AIlabel.style.color = muted;
  AIlabel.style.letterSpacing = ".2px";

  left.appendChild(avatar);
  left.appendChild(AIlabel);

  // Right side: share button
  const shareBtn = document.createElement("button");
  shareBtn.textContent = "Share";
  shareBtn.style.padding = "6px 12px";
  shareBtn.style.border = "none";
  shareBtn.style.borderRadius = "8px";
  shareBtn.style.background = `linear-gradient(90deg, ${accent}, ${accent2})`;
  shareBtn.style.color = "#fff";
  shareBtn.style.fontSize = "12px";
  shareBtn.style.fontWeight = "600";
  shareBtn.style.letterSpacing = ".2px";
  shareBtn.style.boxShadow = shadow;
  shareBtn.style.cursor = "pointer";
  shareBtn.style.transition = "transform .1s ease";
  shareBtn.addEventListener("mouseenter", () => (shareBtn.style.transform = "translateY(-1px)"));
  shareBtn.addEventListener("mouseleave", () => (shareBtn.style.transform = "translateY(0)"));

  footer.appendChild(left);
  footer.appendChild(shareBtn);
  banner.appendChild(footer);

  // Wstawienie przed <h1>
  header.parentNode.insertBefore(banner, header);

  // Animowane wejście
  requestAnimationFrame(() => {
    banner.style.opacity = "1";
    banner.style.transform = "translateY(0)";
  });
}




async function extractAndSendArticle() {
  console.log("Extracting article content with Readability...");

  const clone = document.cloneNode(true);
  const reader = new Readability(clone);
  const article = reader.parse();

  if (!article) {
    console.warn("⚠️ No article content could be extracted. ⚠️");
    return;
  }

  console.log("Sending extracted article to localhost:8000...");

  response = ""
  if (sessionStorage.getItem(window.location.href + "_persona_response")) {
    response = sessionStorage.getItem(window.location.href + "_persona_response");
  } else {
    response = getPersonaResponse(article, "kapitan bomba", "Nie cenzuruj się, używaj wulgaryzmów i mów jak kapitan bomba z kreskówki.");
    sessionStorage.setItem(window.location.href + "_persona_response", await response);
  }

  insertNewHeader(await response);
}
